### ISSUE TITLE
Add routes

### ISSUE THREAD

**Issue by drovak0** [CBaut/kitchen#2]
- [x] GET /items
- [x] GET /items/new
- [x] GET /items/id
- [x] GET /items/id/edit
- [x] POST /items
- [x] PUT /items/id/edit
- [x] DELETE /items/id
- [x] GET /logreg
- [x] POST /log
- [x] POST /reg
- [x] GET /orders/new
- [x] GET /orders
- [x] GET /orders/id
- [x] GET /orders/id/edit
- [x] POST /orders
- [x] PUT /orders/id/edit
- [x] DELETE /orders/id

**Comment by isaac-a-gonzalez** [comment]
https://github.com/CBaut/kitchen/projects/1#card-32031198
