### ISSUE TITLE
Add views (controller)

### ISSUE THREAD

**Issue by drovak0** [CBaut/kitchen#3]
Views
- [x] GET /items/new -> item_new
- [x] GET /items -> item_all
- [x] GET /items/id -> item_view
- [x] GET /items/id/edit -> item_edit
- [x] POST /items -> item_create
- [x] PUT /items/id/edit -> item_update
- [x] DELETE /items/id -> item_delete
- [x] GET /logreg -> log_reg
- [x] POST /log -> login
- [x] POST /reg -> register
- [x] GET /orders/new -> order_new
- [x] GET /orders -> order_all
- [x] GET /orders/id -> order_view
- [x] GET /orders/id/edit -> order_edit
- [x] POST /orders -> order_create
- [x] PUT /orders/id/edit -> order_update
- [x] DELETE /orders/id -> order_delete

**Comment by alexege** [comment]
https://github.com/CBaut/kitchen/pull/7
